spring.application.name=detection-core
server.port=8082
spring.datasource.url=jdbc:mysql://localhost:3306/fraud_detection
spring.datasource.username=root
spring.datasource.password=shyam123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
